version: '3'

services:
  sql2pyspark-api:
    build:
      context: ./backend
    image: sql2pyspark-api
    container_name: sql2pyspark-api
    ports:
      - '5001:5001'
    env_file:
      - ./backend/.env

  sql2pyspark-frontend:
    build:
      context: ./frontend
    image: sql2pyspark-frontend
    container_name: sql2pyspark-frontend
    ports:
      - '3000:3000'
    env_file:
      - ./frontend/.env
 
# To run docker compose file >>>  

# docker-compose up -d --build
## or docker compose up -d --build